var redditResponseComment = [
	{
	"body": "Good. Predatory lending should be banned. If the government isn't going to stop predators, good on Google to step up.",
	"score": 123
	},
	{
	"body": "\"The move also shows the willingness of big tech companies to weigh in on critical policy issues -- and exert their power as the gateways for the internet.\"\n\nI'm happy that payday loan companies are finally being held up as the poster child for fucked-up business, but also fear the day these tech companies will inevitability abuse this ability to exert their power over the masses.",
	"score": 44
	},
	{
	"body": "THE AI TOOK OVER WAAAH",
	"score": 3	
	},
	{
	"body": "N/A",
	"score": "N/A"
	},
	{
	"body": "N/A",
	"score": "N/A"
	},
	{
	"body":"I like Google, hopefully they keep doing good things for humanity.",
	"score": 11
	}
];



var redditResponse = 
{  
   "kind":"Listing",
   "data":{  
      "modhash":"18dntq7py4914e9ab50b1eed3fbbb45539927b7d37645aba99",
      "children":[  
         {  
            "kind":"t3",
            "data":{  
               "domain":"washingtonpost.com",
               "top_comment":redditResponseComment[0],
               "media_embed":{  

               },
               "subreddit":"news",
               "selftext_html":null,
               "selftext":"",
               "likes":null,
               "suggested_sort":null,
               "user_reports":[  

               ],
               "secure_media":null,
               "link_flair_text":null,
               "id":"4ivg2g",
               "from_kind":null,
               "gilded":0,
               "archived":false,
               "clicked":false,
               "report_reasons":null,
               "author":"mbmba",
               "media":null,
               "score":1507,
               "approved_by":null,
               "over_18":false,
               "hidden":false,
               "num_comments":420,
               "thumbnail":"",
               "subreddit_id":"t5_2qh3l",
               "hide_score":false,
               "edited":false,
               "link_flair_css_class":null,
               "author_flair_css_class":null,
               "downs":0,
               "secure_media_embed":{  

               },
               "saved":false,
               "removal_reason":null,
               "stickied":false,
               "from":null,
               "is_self":false,
               "from_id":null,
               "permalink":"/r/news/comments/4ivg2g/google_to_ban_payday_loan_advertisements/",
               "locked":false,
               "name":"t3_4ivg2g",
               "created":1463009316,
               "url":"https://www.washingtonpost.com/news/the-switch/wp/2016/05/11/google-to-ban-payday-loan-advertisements/",
               "author_flair_text":null,
               "quarantine":false,
               "title":"Google to ban payday loan advertisements",
               "created_utc":1462980516,
               "distinguished":null,
               "mod_reports":[  

               ],
               "visited":false,
               "num_reports":null,
               "ups":1507
            }
         },
         {  
            "kind":"t3",
            "data":{  
               "domain":"washingtonpost.com",
               "top_comment": redditResponseComment[5],
               "media_embed":{  

               },
               "subreddit":"business",
               "selftext_html":null,
               "selftext":"",
               "likes":null,
               "suggested_sort":null,
               "user_reports":[  

               ],
               "secure_media":null,
               "link_flair_text":null,
               "id":"4iuxgs",
               "from_kind":null,
               "gilded":0,
               "archived":false,
               "clicked":false,
               "report_reasons":null,
               "author":"dangzal",
               "media":null,
               "score":397,
               "approved_by":null,
               "over_18":false,
               "hidden":false,
               "num_comments":38,
               "thumbnail":"",
               "subreddit_id":"t5_2qgzg",
               "hide_score":false,
               "edited":false,
               "link_flair_css_class":null,
               "author_flair_css_class":null,
               "downs":0,
               "secure_media_embed":{  

               },
               "saved":false,
               "removal_reason":null,
               "stickied":false,
               "from":null,
               "is_self":false,
               "from_id":null,
               "permalink":"/r/business/comments/4iuxgs/google_to_ban_payday_loan_advertisements/",
               "locked":false,
               "name":"t3_4iuxgs",
               "created":1463002624,
               "url":"https://www.washingtonpost.com/news/the-switch/wp/2016/05/11/google-to-ban-payday-loan-advertisements/",
               "author_flair_text":null,
               "quarantine":false,
               "title":"Google to ban payday loan advertisements",
               "created_utc":1462973824,
               "distinguished":null,
               "mod_reports":[  

               ],
               "visited":false,
               "num_reports":null,
               "ups":397
            }
         },
         {  
            "kind":"t3",
            "data":{  
               "domain":"washingtonpost.com",
               "top_comment":redditResponseComment[1],
               "media_embed":{  

               },
               "subreddit":"economy",
               "selftext_html":null,
               "selftext":"",
               "likes":null,
               "suggested_sort":null,
               "user_reports":[  

               ],
               "secure_media":null,
               "link_flair_text":null,
               "id":"4iv2bf",
               "from_kind":null,
               "gilded":0,
               "archived":false,
               "clicked":false,
               "report_reasons":null,
               "author":"TheMacroEvent",
               "media":null,
               "score":67,
               "approved_by":null,
               "over_18":false,
               "hidden":false,
               "num_comments":4,
               "thumbnail":"",
               "subreddit_id":"t5_2qhpn",
               "hide_score":false,
               "edited":false,
               "link_flair_css_class":null,
               "author_flair_css_class":null,
               "downs":0,
               "secure_media_embed":{  

               },
               "saved":false,
               "removal_reason":null,
               "stickied":false,
               "from":null,
               "is_self":false,
               "from_id":null,
               "permalink":"/r/economy/comments/4iv2bf/google_to_ban_payday_loan_advertisements/",
               "locked":false,
               "name":"t3_4iv2bf",
               "created":1463004462,
               "url":"https://www.washingtonpost.com/news/the-switch/wp/2016/05/11/google-to-ban-payday-loan-advertisements/",
               "author_flair_text":null,
               "quarantine":false,
               "title":"Google to ban payday loan advertisements",
               "created_utc":1462975662,
               "distinguished":null,
               "mod_reports":[  

               ],
               "visited":false,
               "num_reports":null,
               "ups":67
            }
         },
         {  
            "kind":"t3",
            "data":{  
               "domain":"washingtonpost.com",
               "top_comment":redditResponseComment[2],
               "media_embed":{  

               },
               "subreddit":"google",
               "selftext_html":null,
               "selftext":"",
               "likes":null,
               "suggested_sort":null,
               "user_reports":[  

               ],
               "secure_media":null,
               "link_flair_text":null,
               "id":"4iw329",
               "from_kind":null,
               "gilded":0,
               "archived":false,
               "clicked":false,
               "report_reasons":null,
               "author":"cos",
               "media":null,
               "score":3,
               "approved_by":null,
               "over_18":false,
               "hidden":false,
               "preview":{  
                  "images":[  
                     {  
                        "source":{  
                           "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?s=104ee07cb837ed901de06f6899a3c336",
                           "width":1484,
                           "height":950
                        },
                        "resolutions":[  
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=f232e2561b43f1b5b02ec9107a1114f2",
                              "width":108,
                              "height":69
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=804033d491cebdf7c15e3e5bbd645556",
                              "width":216,
                              "height":138
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=1c5fbd28ae14d44c571f739baa695c05",
                              "width":320,
                              "height":204
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=eefe2062760e4b24caa36f326bff2e3c",
                              "width":640,
                              "height":409
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=6da14f8d8a31eecd1fa8b779fd6cdcc9",
                              "width":960,
                              "height":614
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=4d14a5315d0e6627bc3221f8ddaf89af",
                              "width":1080,
                              "height":691
                           }
                        ],
                        "variants":{  

                        },
                        "id":"8ve--wvQWybD1GSOnh8raFRPn_GJSoCx9tyBXfgABrQ"
                     }
                  ]
               },
               "num_comments":0,
               "thumbnail":"http://b.thumbs.redditmedia.com/cunRBrZq5jOD0-STvneuTgIujZq8C53KdXTicdJIOAs.jpg",
               "subreddit_id":"t5_2qh45",
               "hide_score":false,
               "edited":false,
               "link_flair_css_class":null,
               "author_flair_css_class":null,
               "downs":0,
               "secure_media_embed":{  

               },
               "saved":false,
               "removal_reason":null,
               "post_hint":"link",
               "stickied":false,
               "from":null,
               "is_self":false,
               "from_id":null,
               "permalink":"/r/google/comments/4iw329/google_to_ban_payday_loan_advertisements/",
               "locked":false,
               "name":"t3_4iw329",
               "created":1463016968,
               "url":"https://www.washingtonpost.com/news/the-switch/wp/2016/05/11/google-to-ban-payday-loan-advertisements/",
               "author_flair_text":null,
               "quarantine":false,
               "title":"Google to ban payday loan advertisements",
               "created_utc":1462988168,
               "distinguished":null,
               "mod_reports":[  

               ],
               "visited":false,
               "num_reports":null,
               "ups":3
            }
         },
         {  
            "kind":"t3",
            "data":{  
               "domain":"washingtonpost.com",
               "top_comment":redditResponseComment[3],
               "media_embed":{  

               },
               "subreddit":"Newsy",
               "selftext_html":null,
               "selftext":"",
               "likes":null,
               "suggested_sort":null,
               "user_reports":[  

               ],
               "secure_media":null,
               "link_flair_text":null,
               "id":"4ivvod",
               "from_kind":null,
               "gilded":0,
               "archived":false,
               "clicked":false,
               "report_reasons":null,
               "author":"newsybot",
               "media":null,
               "score":1,
               "approved_by":null,
               "over_18":false,
               "hidden":false,
               "preview":{  
                  "images":[  
                     {  
                        "source":{  
                           "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?s=104ee07cb837ed901de06f6899a3c336",
                           "width":1484,
                           "height":950
                        },
                        "resolutions":[  
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=f232e2561b43f1b5b02ec9107a1114f2",
                              "width":108,
                              "height":69
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=804033d491cebdf7c15e3e5bbd645556",
                              "width":216,
                              "height":138
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=1c5fbd28ae14d44c571f739baa695c05",
                              "width":320,
                              "height":204
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=eefe2062760e4b24caa36f326bff2e3c",
                              "width":640,
                              "height":409
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=6da14f8d8a31eecd1fa8b779fd6cdcc9",
                              "width":960,
                              "height":614
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=4d14a5315d0e6627bc3221f8ddaf89af",
                              "width":1080,
                              "height":691
                           }
                        ],
                        "variants":{  

                        },
                        "id":"8ve--wvQWybD1GSOnh8raFRPn_GJSoCx9tyBXfgABrQ"
                     }
                  ]
               },
               "num_comments":0,
               "thumbnail":"http://b.thumbs.redditmedia.com/cunRBrZq5jOD0-STvneuTgIujZq8C53KdXTicdJIOAs.jpg",
               "subreddit_id":"t5_2rj90",
               "hide_score":false,
               "edited":false,
               "link_flair_css_class":null,
               "author_flair_css_class":null,
               "downs":0,
               "secure_media_embed":{  

               },
               "saved":false,
               "removal_reason":null,
               "post_hint":"link",
               "stickied":false,
               "from":null,
               "is_self":false,
               "from_id":null,
               "permalink":"/r/Newsy/comments/4ivvod/google_to_ban_payday_loan_advertisements/",
               "locked":false,
               "name":"t3_4ivvod",
               "created":1463014563,
               "url":"https://www.washingtonpost.com/news/the-switch/wp/2016/05/11/google-to-ban-payday-loan-advertisements/",
               "author_flair_text":null,
               "quarantine":false,
               "title":"Google to ban payday loan advertisements",
               "created_utc":1462985763,
               "distinguished":null,
               "mod_reports":[  

               ],
               "visited":false,
               "num_reports":null,
               "ups":1
            }
         },
         {  
            "kind":"t3",
            "data":{  
               "domain":"washingtonpost.com",
               "top_comment":redditResponseComment[4],
               "media_embed":{  

               },
               "subreddit":"Newsbeard",
               "selftext_html":null,
               "selftext":"",
               "likes":null,
               "suggested_sort":null,
               "user_reports":[  

               ],
               "secure_media":null,
               "link_flair_text":null,
               "id":"4iuwaz",
               "from_kind":null,
               "gilded":0,
               "archived":false,
               "clicked":false,
               "report_reasons":null,
               "author":"newsbeard",
               "media":null,
               "score":1,
               "approved_by":null,
               "over_18":false,
               "hidden":false,
               "preview":{  
                  "images":[  
                     {  
                        "source":{  
                           "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?s=104ee07cb837ed901de06f6899a3c336",
                           "width":1484,
                           "height":950
                        },
                        "resolutions":[  
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=f232e2561b43f1b5b02ec9107a1114f2",
                              "width":108,
                              "height":69
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=804033d491cebdf7c15e3e5bbd645556",
                              "width":216,
                              "height":138
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=1c5fbd28ae14d44c571f739baa695c05",
                              "width":320,
                              "height":204
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=eefe2062760e4b24caa36f326bff2e3c",
                              "width":640,
                              "height":409
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=6da14f8d8a31eecd1fa8b779fd6cdcc9",
                              "width":960,
                              "height":614
                           },
                           {  
                              "url":"https://i.redditmedia.com/m8K_i-AE2PhyJHjv4ReNrmDt8WPM2W7Y-igH3cJTU_U.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=4d14a5315d0e6627bc3221f8ddaf89af",
                              "width":1080,
                              "height":691
                           }
                        ],
                        "variants":{  

                        },
                        "id":"8ve--wvQWybD1GSOnh8raFRPn_GJSoCx9tyBXfgABrQ"
                     }
                  ]
               },
               "num_comments":1,
               "thumbnail":"http://b.thumbs.redditmedia.com/cunRBrZq5jOD0-STvneuTgIujZq8C53KdXTicdJIOAs.jpg",
               "subreddit_id":"t5_2zm2r",
               "hide_score":false,
               "edited":false,
               "link_flair_css_class":null,
               "author_flair_css_class":null,
               "downs":0,
               "secure_media_embed":{  

               },
               "saved":false,
               "removal_reason":null,
               "post_hint":"link",
               "stickied":false,
               "from":null,
               "is_self":false,
               "from_id":null,
               "permalink":"/r/Newsbeard/comments/4iuwaz/tech_google_to_ban_payday_loan_advertisements/",
               "locked":false,
               "name":"t3_4iuwaz",
               "created":1463002157,
               "url":"https://www.washingtonpost.com/news/the-switch/wp/2016/05/11/google-to-ban-payday-loan-advertisements/",
               "author_flair_text":null,
               "quarantine":false,
               "title":"[Tech] Google to ban payday loan advertisements",
               "created_utc":1462973357,
               "distinguished":null,
               "mod_reports":[  

               ],
               "visited":false,
               "num_reports":null,
               "ups":1
            }
         }
      ],
      "after":null,
      "before":null
   }
}