var twitterResponseUsers = 
[ { id: 2798497494,
    id_str: '2798497494',
    name: 'jez fernandes',
    screen_name: 'fezjr3',
    location: '',
    description: '',
    url: 'http://t.co/oyUyt3slVr',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 10,
    friends_count: 37,
    listed_count: 8,
    created_at: 'Mon Sep 08 20:02:45 +0000 2014',
    favourites_count: 3,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 2612,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/525004448288882688/FCocmhWx_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/525004448288882688/FCocmhWx_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/2798497494/1415651466',
    profile_link_color: 'DD2E44',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 2884993057,
    id_str: '2884993057',
    name: 'Terry Curry',
    screen_name: 'Autoloansforeve',
    location: 'Mississauga, Ontario',
    description: 'https://t.co/pLDF86GKMf is leading finance company in USA .which is Provides you auto loan with any credit history',
    url: 'http://t.co/16bkIgwuwz',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 263,
    friends_count: 1205,
    listed_count: 9,
    created_at: 'Fri Oct 31 12:05:18 +0000 2014',
    favourites_count: 0,
    utc_offset: -14400,
    time_zone: 'Eastern Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 1438,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/639388524299444224/SZ__c6AR_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/639388524299444224/SZ__c6AR_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/2884993057/1460115752',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 295817800,
    id_str: '295817800',
    name: 'aftab sadiq',
    screen_name: 'aftab_sadiq',
    location: '',
    description: '',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 62,
    friends_count: 34,
    listed_count: 10,
    created_at: 'Mon May 09 18:21:55 +0000 2011',
    favourites_count: 0,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 2774,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/378800000081465043/69a982e5388a3b66e00342c90091534d_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/378800000081465043/69a982e5388a3b66e00342c90091534d_normal.jpeg',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 3299435929,
    id_str: '3299435929',
    name: 'Zoe Cramer',
    screen_name: 'carloanssofast',
    location: 'United States',
    description: 'http://t.co/MgYikAAF95 is one of the leading online auto loan finance service providers \nfor getting car loans in the United States',
    url: 'http://t.co/sONI2ip8Gs',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 65,
    friends_count: 165,
    listed_count: 4,
    created_at: 'Tue Jul 28 10:37:49 +0000 2015',
    favourites_count: 5,
    utc_offset: -25200,
    time_zone: 'Pacific Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 1377,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/625980424628535296/DclmAt7V_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/625980424628535296/DclmAt7V_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/3299435929/1459503475',
    profile_link_color: '4A913C',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 56809304,
    id_str: '56809304',
    name: 'AnonimoMannucci',
    screen_name: 'mannucciao',
    location: 'Italy',
    description: 'Info-Warrior Info-Activist Info-Legionaire Info-Revolutionaire Blogger Self-Publisher 99percenter Anarcho-Democratic \nHuman Being Interstellar Force',
    url: 'http://t.co/JK34umZ32e',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 279,
    friends_count: 449,
    listed_count: 28,
    created_at: 'Tue Jul 14 20:39:50 +0000 2009',
    favourites_count: 3,
    utc_offset: 7200,
    time_zone: 'Rome',
    geo_enabled: false,
    verified: false,
    statuses_count: 28857,
    lang: 'it',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'BF1238',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/388217381/babbo2.jpg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/388217381/babbo2.jpg',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/726740925800652800/2Rgv1Kwu_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/726740925800652800/2Rgv1Kwu_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/56809304/1398261806',
    profile_link_color: '1332BD',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: 'EFEFEF',
    profile_text_color: '333333',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 190166738,
    id_str: '190166738',
    name: 'jess fernandez',
    screen_name: 'forkbender',
    location: 'philippines',
    description: 'im into long distance cycling,running and listening to rock music gardening and raising free range chicken on the side furthermore obsessed w/morrisseys antics',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 66,
    friends_count: 174,
    listed_count: 11,
    created_at: 'Mon Sep 13 07:18:06 +0000 2010',
    favourites_count: 887,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 4303,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/635245436123516928/nZNM2uNH_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/635245436123516928/nZNM2uNH_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/190166738/1440216339',
    profile_link_color: 'DD2E44',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 73979321,
    id_str: '73979321',
    name: 'Esther Coronel de Ib',
    screen_name: 'Esthersuchi',
    location: 'La Paz - Bolivia',
    description: 'The Clarity Mentor-Leadership Consultant for Visionary Leaders, I Mentor U2 Find ur Purpose/Mission/Vision/Passion! EXECUTIVE COACHING available',
    url: 'http://t.co/MxiYFMtI2X',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 1242,
    friends_count: 1997,
    listed_count: 77,
    created_at: 'Sun Sep 13 21:28:45 +0000 2009',
    favourites_count: 573,
    utc_offset: -14400,
    time_zone: 'La Paz',
    geo_enabled: false,
    verified: false,
    statuses_count: 68240,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'B2DFDA',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme13/bg.gif',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme13/bg.gif',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/3178184273/cbabf564df6863af0bc74c2a00bd0f5c_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/3178184273/cbabf564df6863af0bc74c2a00bd0f5c_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/73979321/1409183679',
    profile_link_color: '93A644',
    profile_sidebar_border_color: 'EEEEEE',
    profile_sidebar_fill_color: 'FFFFFF',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 14641650,
    id_str: '14641650',
    name: 'Well Spoken Bocan',
    screen_name: 'paulsteven',
    location: 'Delray Beach,FL,USA☀️',
    description: '#RIT #STAC ACB @westbocatm https://t.co/Vh3JEFdpkP 561-302-0051 txt or visit https://t.co/cjKPHso2Q3 #westbocaTM https://t.co/fHHSHUKPRn',
    url: 'https://t.co/zL1rfuLjYL',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 99858,
    friends_count: 51637,
    listed_count: 394,
    created_at: 'Sat May 03 21:24:48 +0000 2008',
    favourites_count: 46692,
    utc_offset: -14400,
    time_zone: 'Eastern Time (US & Canada)',
    geo_enabled: true,
    verified: false,
    statuses_count: 57049,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '131516',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000173405563/ln9O4_V2.jpeg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000173405563/ln9O4_V2.jpeg',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/717015229075468288/dAGn0muQ_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/717015229075468288/dAGn0muQ_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/14641650/1460730896',
    profile_link_color: '0000FF',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: 'EFEFEF',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 2408257543,
    id_str: '2408257543',
    name: 'Omega Stereo Radio',
    screen_name: 'omegaradioco',
    location: 'Bogota',
    description: 'Emisora Institucional de Fundación Colombia Nuevos Horizontes  (https://t.co/KZXjb2ejmn)',
    url: 'https://t.co/JCxoDm7TVq',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 511,
    friends_count: 1950,
    listed_count: 75,
    created_at: 'Mon Mar 24 03:15:54 +0000 2014',
    favourites_count: 29,
    utc_offset: -18000,
    time_zone: 'Bogota',
    geo_enabled: true,
    verified: false,
    statuses_count: 106878,
    lang: 'es',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '89C9FA',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/582776707498655745/sQSii8jE.jpg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/582776707498655745/sQSii8jE.jpg',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/590764944796291072/kHc9Gs1u_normal.png',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/590764944796291072/kHc9Gs1u_normal.png',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/2408257543/1421736568',
    profile_link_color: 'FA743E',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 822111926,
    id_str: '822111926',
    name: 'KY Equal Justice',
    screen_name: 'KYEqualJustice',
    location: 'Lexington, KY',
    description: 'Advocates and watchdogs for low income Kentuckians. Follows, likes &RTs do not imply endorsement or agreement.',
    url: 'https://t.co/ojHmwY3hNQ',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 851,
    friends_count: 1224,
    listed_count: 28,
    created_at: 'Thu Sep 13 20:08:57 +0000 2012',
    favourites_count: 520,
    utc_offset: -10800,
    time_zone: 'Atlantic Time (Canada)',
    geo_enabled: true,
    verified: false,
    statuses_count: 1146,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/2606663188/0l9p5wjnp33deuctino1_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/2606663188/0l9p5wjnp33deuctino1_normal.jpeg',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 15718600,
    id_str: '15718600',
    name: 'Steven R Clark',
    screen_name: 'maelorin',
    location: 'Adelaide, Australia',
    description: 'specialist generalist: lawyer, technologist, teacher, academic || technology, regulation, policy, practice || genderfluid aspie || *seeking PhD/SJD programme*',
    url: 'http://t.co/q3hmOv0CnR',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 1348,
    friends_count: 2281,
    listed_count: 540,
    created_at: 'Mon Aug 04 05:13:47 +0000 2008',
    favourites_count: 65540,
    utc_offset: 34200,
    time_zone: 'Adelaide',
    geo_enabled: true,
    verified: false,
    statuses_count: 68382,
    lang: 'en-gb',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '131516',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
    profile_background_tile: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/645283976504971264/PZ08sMya_normal.png',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/645283976504971264/PZ08sMya_normal.png',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/15718600/1442245620',
    profile_link_color: '333333',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: 'EFEFEF',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 6244132,
    id_str: '6244132',
    name: 'amberlynne',
    screen_name: 'amberlynne',
    location: 'Washington, DC',
    description: 'likes: the caps. the nats. nail polish. batman. zambonis. glitter. drinking tea. pants that fit. making love out of nothing at all. dislikes: 99% of PA.',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 284,
    friends_count: 652,
    listed_count: 31,
    created_at: 'Tue May 22 20:56:52 +0000 2007',
    favourites_count: 16205,
    utc_offset: -14400,
    time_zone: 'America/New_York',
    geo_enabled: false,
    verified: false,
    statuses_count: 22584,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/618804070950809600/u7OvA5bF.jpg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/618804070950809600/u7OvA5bF.jpg',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/417759030715875329/S7LVL45P_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/417759030715875329/S7LVL45P_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/6244132/1400291282',
    profile_link_color: 'D6130D',
    profile_sidebar_border_color: 'FFFFFF',
    profile_sidebar_fill_color: 'C0DFEC',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 22846618,
    id_str: '22846618',
    name: 'lehi',
    screen_name: 'lehimesa',
    location: 'arizona',
    description: 'artist mom granny wife teacher caretaker mule friend farm worker cat herder dog lover bird watcher voter. Pres Obama will be in history books forever!',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 5122,
    friends_count: 5636,
    listed_count: 591,
    created_at: 'Wed Mar 04 22:33:48 +0000 2009',
    favourites_count: 145199,
    utc_offset: -25200,
    time_zone: 'Pacific Time (US & Canada)',
    geo_enabled: true,
    verified: false,
    statuses_count: 272377,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C6E2EE',
    profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/303563636/SARAHSCORN.jpg',
    profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/303563636/SARAHSCORN.jpg',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/470021506941333504/kedO9k2Q_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/470021506941333504/kedO9k2Q_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/22846618/1386981259',
    profile_link_color: '1F98C7',
    profile_sidebar_border_color: 'C6E2EE',
    profile_sidebar_fill_color: 'DAECF4',
    profile_text_color: '663B12',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 141231782,
    id_str: '141231782',
    name: 'Patricia Hasson',
    screen_name: 'pattyhasson',
    location: 'Phila',
    description: '',
    url: 'http://t.co/OMv4lZtv8b',
    entities: { url: [Object], description: [Object] },
    protected: false,
    followers_count: 84,
    friends_count: 76,
    listed_count: 7,
    created_at: 'Fri May 07 14:22:50 +0000 2010',
    favourites_count: 55,
    utc_offset: -14400,
    time_zone: 'Eastern Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 452,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/699985191092285442/P6-1K5F2_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/699985191092285442/P6-1K5F2_normal.jpg',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false },
  { id: 104312486,
    id_str: '104312486',
    name: 'Susan Lee',
    screen_name: 'nykimchi',
    location: 'N 40°46\' 0\'\' / W 73°59\' 0\'\'',
    description: '',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 172,
    friends_count: 465,
    listed_count: 11,
    created_at: 'Tue Jan 12 23:53:07 +0000 2010',
    favourites_count: 4331,
    utc_offset: -10800,
    time_zone: 'Atlantic Time (Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 10656,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/519668506569093124/qvpxvRBz_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/519668506569093124/qvpxvRBz_normal.jpeg',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false } ]



var twitterResponse = 
{ statuses: 
   [ { created_at: 'Wed May 11 22:38:04 +0000 2016',
       id: 730527420965658600,
       id_str: '730527420965658624',
       text: 'Clients of pay day loan companies are not looking for those businesses through Google searches. They\'re finding... https://t.co/3dtzCZOnBw',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://www.facebook.com/twitter" rel="nofollow">Facebook</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[0],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:34:03 +0000 2016',
       id: 730526411354603500,
       id_str: '730526411354603520',
       text: 'RT @jbouie: Good for Google on banning advertisements for payday loan companies. https://t.co/RlqWcGgWBi',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[1],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 41,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:33:03 +0000 2016',
       id: 730526158081667100,
       id_str: '730526158081667073',
       text: 'Google to ban payday loan advertisements\nhttps://t.co/4EPKkjS1Nz https://t.co/w6iL8vm69m',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[2],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:33:00 +0000 2016',
       id: 730526147847573500,
       id_str: '730526147847573504',
       text: 'RT @breakingmoney: Google to ban all payday loan ads from its site - Wall Street Journal https://t.co/gXeHhDTJL8',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[3],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 132,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:25:56 +0000 2016',
       id: 730524366178549800,
       id_str: '730524366178549760',
       text: 'A good move but low-income folks still need loans. Google to ban payday loan advertisements - The Washington Post https://t.co/i9g5RaoOSQ',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[4],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:23:54 +0000 2016',
       id: 730523857292005400,
       id_str: '730523857292005376',
       text: 'RT @RepJohnConyers: Pleased to learn @google will ban payday loans from its advertising systems. https://t.co/vxzPAyOd8y',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="https://roundteam.co" rel="nofollow">RoundTeam</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[5],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:23:29 +0000 2016',
       id: 730523752300216300,
       id_str: '730523752300216320',
       text: 'RT @RepJohnConyers: Pleased to learn @google will ban payday loans from its advertising systems. https://t.co/vxzPAyOd8y',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[6],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:22:13 +0000 2016',
       id: 730523431721009200,
       id_str: '730523431721009152',
       text: 'RT @RepJohnConyers: Pleased to learn @google will ban payday loans from its advertising systems. https://t.co/vxzPAyOd8y',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://dlvr.it" rel="nofollow">dlvr.it</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[7],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:21:56 +0000 2016',
       id: 730523362779336700,
       id_str: '730523362779336704',
       text: 'RT @breakingmoney: Google to ban all payday loan ads from its site - Wall Street Journal https://t.co/gXeHhDTJL8',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[8],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 132,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:21:07 +0000 2016',
       id: 730523157031981000,
       id_str: '730523157031981057',
       text: 'RT @RepJohnConyers: Pleased to learn @google will ban payday loans from its advertising systems. https://t.co/vxzPAyOd8y',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="https://mobile.twitter.com" rel="nofollow">Mobile Web (M5)</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[9],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:20:05 +0000 2016',
       id: 730522896867582000,
       id_str: '730522896867581953',
       text: 'RT @RepJohnConyers: Pleased to learn @google will ban payday loans from its advertising systems. https://t.co/vxzPAyOd8y',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[10],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:19:17 +0000 2016',
       id: 730522692500197400,
       id_str: '730522692500197376',
       text: 'Pleased to learn @google will ban payday loans from its advertising systems. https://t.co/vxzPAyOd8y',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[11],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 5,
       favorite_count: 5,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:18:21 +0000 2016',
       id: 730522461217935400,
       id_str: '730522461217935361',
       text: 'RT @breakingmoney: Google to ban all payday loan ads from its site - Wall Street Journal https://t.co/gXeHhDTJL8',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[12],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 132,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:17:42 +0000 2016',
       id: 730522298021609500,
       id_str: '730522298021609474',
       text: 'RT @WestLondonMan: Whoever did the organizing for this-great job! Google bans/blocks payday lenders ads https://t.co/dHV016Croq',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[13],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 4,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Wed May 11 22:14:30 +0000 2016',
       id: 730521491788464100,
       id_str: '730521491788464129',
       text: 'RT @breakingmoney: Google to ban all payday loan ads from its site - Wall Street Journal https://t.co/gXeHhDTJL8',
       entities: [Object],
       truncated: false,
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: twitterResponseUsers[14],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 132,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' } ],
  search_metadata: 
   { completed_in: 0.213,
     max_id: 730527420965658600,
     max_id_str: '730527420965658624',
     next_results: '?max_id=730521491788464128&q=https%3A%2F%2Fwww.washingtonpost.com%2Fnews%2Fthe-switch%2Fwp%2F2016%2F05%2F11%2Fgoogle-to-ban-payday-loan-advertisements%2F&include_entities=1',
     query: 'https%3A%2F%2Fwww.washingtonpost.com%2Fnews%2Fthe-switch%2Fwp%2F2016%2F05%2F11%2Fgoogle-to-ban-payday-loan-advertisements%2F',
     refresh_url: '?since_id=730527420965658624&q=https%3A%2F%2Fwww.washingtonpost.com%2Fnews%2Fthe-switch%2Fwp%2F2016%2F05%2F11%2Fgoogle-to-ban-payday-loan-advertisements%2F&include_entities=1',
     count: 15,
     since_id: 0,
     since_id_str: '0' } 
 }

